# Generated by Django 4.2.4 on 2023-10-16 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_alter_bid_listing_alter_listing_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='url',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
