# Generated by Django 4.2.4 on 2023-10-28 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0008_alter_user_watchlist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='watchlist',
            field=models.ManyToManyField(blank=True, default='null', null=True, related_name='+', to='auctions.listing'),
        ),
    ]
