# Generated by Django 4.2.4 on 2023-11-05 06:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0011_bid_user_alter_bid_listing'),
    ]

    operations = [
        migrations.AddField(
            model_name='bid',
            name='current_bidder',
            field=models.ForeignKey(default='benton', on_delete=django.db.models.deletion.CASCADE, related_name='current_bidder', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
