# Generated by Django 4.2.4 on 2023-11-05 06:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0012_bid_current_bidder'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bid',
            name='current_bidder',
        ),
    ]
